select * 
from (
select  "HZ_PARTIES"."PARTY_ID" as "PARTY_ID_PARTIES",
"HZ_PARTIES"."PRIMARY_PHONE_NUMBER" as "PHONE NUMBER",
"HZ_PARTIES"."PRIMARY_PHONE_AREA_CODE" as "PHONE AREA CODE",
"HZ_PARTIES"."PRIMARY_PHONE_COUNTRY_CODE" as "PHONE COUNTRY CODE",
"HZ_PARTIES"."PRIMARY_PHONE_LINE_TYPE" as "Indicates as Faxable:",
"HZ_CUSTOMER_PROFILES_F"."CREDIT_CURRENCY_CODE" as "Currency",
"HZ_CUSTOMER_PROFILES_F"."CREDIT_LIMIT" as "Credit Limit",
"HZ_CUSTOMER_PROFILES_F"."STANDARD_TERMS" as "Payment Terms",
"HZ_CUST_ACCOUNTS"."TAX_CODE" as "TAX_CODE",
"HZ_CUST_ACCOUNTS"."ACCOUNT_ESTABLISHED_DATE" as "Account Created Date",
"HZ_CUSTOMER_PROFILES_F"."CUST_ACCOUNT_PROFILE_ID" as "Cust_ACCT_PROFILE_ID",
"HZ_CUST_ACCOUNTS"."CUST_ACCOUNT_ID" as "CUST_ACCT_ID",
-- "HZ_CUST_ACCOUNTS"."PARTY_ID" as "PARTY_ID_Cust_ACCTS",
"HZ_PARTY_SITES"."PARTY_SITE_ID" as "PARTY_SITE_ID",
"HZ_PARTY_SITES"."OVERALL_PRIMARY_FLAG" as "OVERALL_PRIMARY_FLAG",
--"HZ_PARTY_SITES"."LOCATION_ID" as "LOCATION_ID_FROM_PARTY_SITES",
"HZ_PARTIES"."PARTY_NAME" as "PARTY_NAME",	  
	 "HZ_LOCATIONS"."LOCATION_ID" as "LOCATION_ID_FROM_LOCATION",
	 "HZ_LOCATIONS"."ADDRESS1" as "ADDRESS1",
	 "HZ_LOCATIONS"."CITY" as "CITY",
	 "HZ_LOCATIONS"."COUNTRY" as "COUNTRY",
	 "HZ_LOCATIONS"."POSTAL_CODE" as "ZIP_CODE",
	 "HZ_CUST_ACCOUNTS"."ATTRIBUTE1" as "ATTRIBUTE1 _CUST_ACCTS_ACCT NUMBER" ,
 "HZ_CUST_ACCOUNTS"."ACCOUNT_NUMBER" as "ACCOUNT NUMBER_CUST_ACCTS",
ROW_NUMBER() OVER(PARTITION BY "HZ_PARTIES"."PARTY_NAME" ORDER BY "HZ_PARTIES"."PARTY_NAME" ) as "row_number"
 from	"FUSION"."HZ_PARTIES" "HZ_PARTIES",
	"FUSION"."HZ_LOCATIONS" "HZ_LOCATIONS",
	"FUSION"."HZ_PARTY_SITES" "HZ_PARTY_SITES" ,
"FUSION"."HZ_CUST_ACCOUNTS" "HZ_CUST_ACCOUNTS",
"FUSION"."HZ_CUST_ACCT_SITES_ALL" "HZ_CUST_ACCT_SITES_ALL",
"FUSION"."HZ_CUSTOMER_PROFILES_F" "HZ_CUSTOMER_PROFILES_F"


WHERE "HZ_PARTY_SITES"."PARTY_ID" = "HZ_PARTIES"."PARTY_ID"
and "HZ_LOCATIONS"."LOCATION_ID"="HZ_PARTY_SITES"."LOCATION_ID"
and "HZ_CUST_ACCOUNTS"."PARTY_ID" = "HZ_PARTIES"."PARTY_ID"
and "HZ_CUST_ACCT_SITES_ALL"."PARTY_SITE_ID" = "HZ_PARTY_SITES"."PARTY_SITE_ID"
and "HZ_CUST_ACCT_SITES_ALL"."CUST_ACCOUNT_ID" = "HZ_CUST_ACCOUNTS"."CUST_ACCOUNT_ID"
and
"HZ_CUST_ACCOUNTS"."CUST_ACCOUNT_ID" = "HZ_CUSTOMER_PROFILES_F"."CUST_ACCOUNT_ID"

)

--where "row_number"= 1